### ISSUE TITLE
not woking after installation on HA 2023.12.4

### ISSUE THREAD

**Issue by SpeedlimitsB** [ThaStealth/alfen_modbus#2]
All entitys are unavailble .

If i do a manual modbus integration it works . 

log : 

2023-12-27 19:56:45.693 INFO (MainThread) [homeassistant.setup] Setting up alfen_modbus
2023-12-27 19:56:45.694 INFO (MainThread) [homeassistant.setup] Setup of domain alfen_modbus took 0.0 seconds
2023-12-27 19:56:45.746 INFO (MainThread) [homeassistant.components.number] Setting up number.alfen_modbus
2023-12-27 19:56:45.749 INFO (MainThread) [homeassistant.components.select] Setting up select.alfen_modbus
2023-12-27 19:56:45.750 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new number.alfen_modbus entity: number.alfen_max_current_limit_s1
2023-12-27 19:56:45.759 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.alfen_modbus
2023-12-27 19:56:45.784 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new select.alfen_modbus entity: select.alfen_usable_phases1
2023-12-27 19:56:45.789 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_name
2023-12-27 19:56:45.797 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_manufacturer
2023-12-27 19:56:45.799 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_modbus_table_version
2023-12-27 19:56:45.807 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_firmware_version
2023-12-27 19:56:45.814 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_platform_type
2023-12-27 19:56:45.817 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_serial
2023-12-27 19:56:45.819 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_current_time
2023-12-27 19:56:45.828 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_last_boot
2023-12-27 19:56:45.830 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_actual_max_current
2023-12-27 19:56:45.835 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_board_temperature
2023-12-27 19:56:45.838 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_backoffice_connected
2023-12-27 19:56:45.840 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_number_of_sockets
2023-12-27 19:56:45.846 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_meter_state
2023-12-27 19:56:45.855 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_meter_reading_age
2023-12-27 19:56:45.858 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_meter_type
2023-12-27 19:56:45.860 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_voltage_l1_n
2023-12-27 19:56:45.863 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_voltage_l2_n
2023-12-27 19:56:45.869 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_voltage_l3_n
2023-12-27 19:56:45.876 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_voltage_l1_l2
2023-12-27 19:56:45.879 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_voltage_l2_l3
2023-12-27 19:56:45.884 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_voltage_l3_l1
2023-12-27 19:56:45.886 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_current_n
2023-12-27 19:56:45.890 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_current_l1
2023-12-27 19:56:45.893 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_current_l2
2023-12-27 19:56:45.899 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_current_l3
2023-12-27 19:56:45.902 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_current_total
2023-12-27 19:56:45.905 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_power_factor_l1
2023-12-27 19:56:45.911 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_power_factor_l2
2023-12-27 19:56:45.914 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_power_factor_l3
2023-12-27 19:56:45.917 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_power_factor_sum
2023-12-27 19:56:45.919 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_frequency
2023-12-27 19:56:45.925 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_power_l1
2023-12-27 19:56:45.934 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_power_l2
2023-12-27 19:56:45.937 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_power_l3
2023-12-27 19:56:45.941 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_power_sum
2023-12-27 19:56:45.944 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_apparant_power_l1
2023-12-27 19:56:45.947 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_apparant_power_l2
2023-12-27 19:56:45.949 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_apparant_power_l3
2023-12-27 19:56:45.956 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_apparant_power_sum
2023-12-27 19:56:45.959 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_reactive_power_l1
2023-12-27 19:56:45.961 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_reactive_power_l2
2023-12-27 19:56:45.964 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_reactive_power_l3
2023-12-27 19:56:45.970 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_reactive_power_sum
2023-12-27 19:56:45.973 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_energy_delivered_l1
2023-12-27 19:56:45.977 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_energy_delivered_l2
2023-12-27 19:56:45.980 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_energy_delivered_l3
2023-12-27 19:56:45.985 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_energy_delivered_sum
2023-12-27 19:56:45.987 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_energy_consumed_l1
2023-12-27 19:56:45.993 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_energy_consumed_l2
2023-12-27 19:56:45.995 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_energy_consumed_l3
2023-12-27 19:56:45.998 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_real_energy_consumed_sum
2023-12-27 19:56:46.001 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_apparant_energy_l1
2023-12-27 19:56:46.010 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_apparant_energy_l2
2023-12-27 19:56:46.013 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_apparant_energy_l3
2023-12-27 19:56:46.016 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_apparant_energy_sum
2023-12-27 19:56:46.021 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_reactive_energy_l1
2023-12-27 19:56:46.024 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_reactive_energy_l2
2023-12-27 19:56:46.027 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_reactive_energy_l3
2023-12-27 19:56:46.033 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_reactive_energy_sum
2023-12-27 19:56:46.036 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_availability
2023-12-27 19:56:46.044 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_mode_3_state
2023-12-27 19:56:46.047 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_actual_applied_max_current
2023-12-27 19:56:46.052 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_max_current_valid_time
2023-12-27 19:56:46.055 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_max_current
2023-12-27 19:56:46.061 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_active_load_balacing_safe_current
2023-12-27 19:56:46.063 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_received_sp_accounted_for
2023-12-27 19:56:46.069 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_charging_mode
2023-12-27 19:56:46.071 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_car_charging
2023-12-27 19:56:46.076 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_car_connected
2023-12-27 19:56:46.079 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_current_session_wh
2023-12-27 19:56:46.083 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alfen_modbus entity: sensor.alfen_current_session_duration
2023-12-27 19:57:16.001 ERROR (MainThread) [custom_components.alfen_modbus] Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/alfen_modbus/__init__.py", line 192, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_modbus/__init__.py", line 251, in read_modbus_data
    and self.read_modbus_data_station()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_modbus/__init__.py", line 268, in read_modbus_data_station
    status_data.registers, byteorder=Endian.c
                                     ^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: c
2023-12-27 19:57:45.999 ERROR (MainThread) [custom_components.alfen_modbus] Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/alfen_modbus/__init__.py", line 192, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_modbus/__init__.py", line 251, in read_modbus_data
    and self.read_modbus_data_station()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_modbus/__init__.py", line 268, in read_modbus_data_station
    status_data.registers, byteorder=Endian.c
                                     ^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: c
2023-12-27 19:58:15.999 ERROR (MainThread) [custom_components.alfen_modbus] Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/alfen_modbus/__init__.py", line 192, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_modbus/__init__.py", line 251, in read_modbus_data
    and self.read_modbus_data_station()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_modbus/__init__.py", line 268, in read_modbus_data_station
    status_data.registers, byteorder=Endian.c
                                     ^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: c
2023-12-27 19:58:45.998 ERROR (MainThread) [custom_components.alfen_modbus] Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/alfen_modbus/__init__.py", line 192, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_modbus/__init__.py", line 251, in read_modbus_data
    and self.read_modbus_data_station()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_modbus/__init__.py", line 268, in read_modbus_data_station
    status_data.registers, byteorder=Endian.c
                                     ^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: c
2023-12-27 19:59:08.712 DEBUG (MainThread) [custom_components.alfen_modbus] Setup alfen_modbus.alfen
2023-12-27 19:59:08.736 INFO (MainThread) [homeassistant.components.number] Setting up number.alfen_modbus
2023-12-27 19:59:08.737 INFO (MainThread) [homeassistant.components.select] Setting up select.alfen_modbus
2023-12-27 19:59:08.738 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.alfen_modbus

**Comment by SpeedlimitsB** [comment]
btw;
what do you mean by modbus adress during setup ?
i left it to 200

**Comment by SpeedlimitsB** [comment]
![image](https://github.com/ThaStealth/alfen_modbus/assets/30408053/e44c7c8c-d5da-4000-9092-a814a92b1701)

**Comment by ThaStealth** [comment]
Hi,

I seem to have made a mistake when fixing the pymodbus bump to 3.5.4. I fixed it in 0.1.2. Can you install the new version and let me know if it is fixed?

Alfen specifies in their documentation that the Modbus address of the charger is 200. However, they are able to change this in the future, so this is just a precaution. Normally you don't need to change it

**Comment by SpeedlimitsB** [comment]
Now I have connections and data.
Thanks for the effort!!
